# Generated by Django 2.2.1 on 2019-05-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_trackedrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='stripe_subscription_item_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
