# Generated by Django 2.2.1 on 2019-05-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_membership_stripe_subscription_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedrequest',
            name='usage_record_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
